# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWSXgQxNp2fyx3pAt0letdsERDIzq6m4
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

zip_path = "/content/drive/MyDrive/yolo_dataset.zip"
extract_path = "/content/yolodataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Dataset extracted to", extract_path)

yaml_content = """
path: /content/yolodataset/yolo_dataset
train: images/train
val: images/val
test: images/test

nc: 1
names: ["number_plate"]
"""

with open("/content/yolodataset/number_plate.yaml", "w") as f:
    f.write(yaml_content)

print("✅ YAML created")

pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(
    data="/content/yolodataset/number_plate.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    name="number_plate_detector"
)

from ultralytics import YOLO

model = YOLO("/content/runs/detect/number_plate_detector3/weights/best.pt")
results = model.predict("/content/drive/MyDrive/Skoda-Superb-road-India.jpg", save=True, conf=0.5)

!zip -r best_model.zip runs/detect/number_plate_detector3/weights/best.pt

from google.colab import files
files.download("best_model.zip")

